version: '3.7'

services:
  proxy:
    volumes:
      - ./proxy/nginx-dev.conf:/etc/nginx/nginx.conf

  server:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    command: npm run local:dev
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
      - '9229:9229'

  postgresql:
    ports:
      - '5432:5432'

  admin:
    ports:
      - '3001:3001'
