# Build
FROM node:14.15.4-alpine3.12 AS build
RUN apk update && apk add --no-cache git
WORKDIR /app/admin
RUN git clone https://github.com/Rastraponovich/weekend-ogranizer-admin /app/admin/
COPY ./.env .
RUN npm install && npm cache clean --force && npm run build

FROM nginx:1.19.6-alpine AS release
COPY --from=build /app/admin/build /usr/share/nginx/html